[package]
name = "ssh-auth-github"
version = "0.1.0"
authors = ["Erik Dalén <erik.gustav.dalen@gmail.com>"]

[dependencies]
reqwest = "0.10.8"
serde_json = "1.0.16"
serde_derive = "1.0.43"
serde = "1.0.43"
